In [73]:
import os
import pandas as pd

# Chemin du dossier contenant les fichiers de données
dossier_datasets = "data"

# Liste des fichiers dans le dossier
fichiers = os.listdir(dossier_datasets)

# Filtrer les fichiers CSV
fichiers_csv = [fichier for fichier in fichiers if fichier.endswith(".csv")]

# Parcourir chaque fichier CSV et afficher les informations
for fichier in fichiers_csv:
    chemin_fichier = os.path.join(dossier_datasets, fichier)
    print(f"Informations pour le fichier : {fichier}")
    # Charger le fichier CSV dans un DataFrame
    df = pd.read_csv(chemin_fichier)
    
      # Afficher les premières lignes du DataFrame
    print("Premières lignes :")
    print(df.head())
    print()

    print("Informations sur le DataFrame :")
    print(df.info())
    print()

Informations pour le fichier : olist_customers_dataset.csv
Premières lignes :
                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 franca             SP
1                      9790  sao bernardo do campo             SP
2                      1151              sao paulo             SP
3                      8775        mogi das cruzes             SP
4                     13056               campinas             SP

Informations sur le DataFrame :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB
None

Informations pour le fichier : olist_geolocation_dataset.csv
Premières lignes :
   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                         1037       -23.545621       -46.639292
1                         1046       -23.546081       -46.644820
2                         1046       -23.546129       -46.642951
3                         1041       -23.544392       -46.639499
4                         1035       -23.541578       -46.641607

  geolocation_city geolocation_state
0        sao paulo                SP
1        sao paulo                SP
2        sao paulo                SP
3        sao paulo                SP
4        sao paulo                SP

Informations sur le DataFrame :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB
None

Informations pour le fichier : olist_orders_dataset.csv
Premières lignes :
                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date
0           2017-10-18 00:00:00
1           2018-08-13 00:00:00
2           2018-09-04 00:00:00
3           2017-12-15 00:00:00
4           2018-02-26 00:00:00

Informations sur le DataFrame :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB
None

Informations pour le fichier : olist_order_items_dataset.csv
Premières lignes :
                           order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1
1  00018f77f2f0320c557190d7a144bdd3              1
2  000229ec398224ef6ca0657da4fc703e              1
3  00024acbcdf0a6daa1e931b038114c75              1
4  00042b26cf59d7ce69dfabb4e55b4fd9              1

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
3  7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
4  ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87

   shipping_limit_date   price  freight_value
0  2017-09-19 09:45:35   58.90          13.29
1  2017-05-03 11:05:13  239.90          19.93
2  2018-01-18 14:48:30  199.00          17.87
3  2018-08-15 10:10:18   12.99          12.79
4  2017-02-13 13:57:51  199.90          18.14

Informations sur le DataFrame :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB
None

Informations pour le fichier : olist_order_payments_dataset.csv
Premières lignes :
                           order_id  payment_sequential payment_type  \
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card

   payment_installments  payment_value
0                     8          99.33
1                     1          24.39
2                     1          65.71
3                     8         107.78
4                     2         128.45

Informations sur le DataFrame :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB
None

Informations pour le fichier : olist_order_reviews_dataset.csv
Premières lignes :
                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1

   review_score review_comment_title  \
0             4                  NaN
1             5                  NaN
2             5                  NaN
3             5                  NaN
4             5                  NaN

                              review_comment_message review_creation_date  \
0                                                NaN  2018-01-18 00:00:00
1                                                NaN  2018-03-10 00:00:00
2                                                NaN  2018-02-17 00:00:00
3              Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00
4  Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00

  review_answer_timestamp
0     2018-01-18 21:46:59
1     2018-03-11 03:05:13
2     2018-02-18 14:36:24
3     2017-04-21 22:02:06
4     2018-03-02 10:26:53

Informations sur le DataFrame :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB
None

Informations pour le fichier : olist_products_dataset.csv
Premières lignes :
                         product_id  product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria
1  3aa071139cb16b67ca9e5dea641aaa2f                  artes
2  96bd76ec8810374ed1b65e291975717f          esporte_lazer
3  cef67bcfe19066a932b7673e239eb23d                  bebes
4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0
1                 44.0                       276.0                 1.0
2                 46.0                       250.0                 1.0
3                 27.0                       261.0                 1.0
4                 37.0                       402.0                 4.0

   product_weight_g  product_length_cm  product_height_cm  product_width_cm
0             225.0               16.0               10.0              14.0
1            1000.0               30.0               18.0              20.0
2             154.0               18.0                9.0              15.0
3             371.0               26.0                4.0              26.0
4             625.0               20.0               17.0              13.0

Informations sur le DataFrame :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB
None

Informations pour le fichier : olist_sellers_dataset.csv
Premières lignes :
                          seller_id  seller_zip_code_prefix  \
0  3442f8959a84dea7ee197c632cb2df15                   13023
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914

         seller_city seller_state
0           campinas           SP
1         mogi guacu           SP
2     rio de janeiro           RJ
3          sao paulo           SP
4  braganca paulista           SP

Informations sur le DataFrame :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB
None

Informations pour le fichier : product_category_name_translation.csv
Premières lignes :
    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

Informations sur le DataFrame :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB
None

Question 1 : Méthodes supervisées pour la segmentation marketing

Il existe plusieurs méthodes des algorithmes non supervisés: <br>
-Méthode de K-moyennes  <br>
-Clustering hiérarchique  <br>
-Analyse en composantes principales (ACP)  <br>
-Classification K-Means  <br>
-Classification des documents   <br>

Question 4 : Quels clients payent le plus de frais de livraison ?

In [74]:
dossier = "data"

### Exploration de données

In [75]:
df_items = pd.read_csv(f"{dossier}/olist_order_items_dataset.csv")
df_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [76]:
df_orders = pd.read_csv(f"{dossier}/olist_orders_dataset.csv")
df_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [77]:
df_products = pd.read_csv(f"{dossier}/olist_products_dataset.csv")
df_products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [78]:
df_traduction_products = pd.read_csv('data/product_category_name_translation.csv')
df_traduction_products.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

### Nettoyage de données

##### Renommer les colonnes

In [79]:
df_items = df_items.rename(columns={
    'order_id': 'identifiant_commande',
    'order_item_id': 'identifiant_article_commande',
    'product_id': 'identifiant_produit',
    'seller_id': 'identifiant_vendeur',
    'shipping_limit_date': 'date_limite_expedition',
    'price': 'prix',
    'freight_value': 'valeur_fret'
})

# Renommer les colonnes
df_orders = df_orders.rename(columns={
    'order_id': 'identifiant_commande',
    'customer_id': 'identifiant_client',
    'order_status': 'statut_commande',
    'order_purchase_timestamp': 'timestamp_achat_commande',
    'order_approved_at': 'commande_approuvee_a',
    'order_delivered_carrier_date': 'date_livraison_transporteur_commande',
    'order_delivered_customer_date': 'date_livraison_client_commande',
    'order_estimated_delivery_date': 'date_livraison_estimee_commande'
})

df_products = df_products.rename(columns={
    'product_id': 'identifiant_produit',
    'product_category_name': 'nom_categorie_produit',
    'product_name_lenght': 'longueur_nom_produit',
    'product_description_lenght': 'longueur_description_produit',
    'product_photos_qty': 'quantite_photos_produit',
    'product_weight_g': 'poids_produit_g',
    'product_length_cm': 'longueur_produit_cm',
    'product_height_cm': 'hauteur_produit_cm',
    'product_width_cm': 'largeur_produit_cm'
})

df_traduction_products = df_traduction_products.rename(columns={
    'product_category_name': 'nom_categorie_produit',
    'product_category_name_english': 'nom_categorie_produit_anglais'
})

Nous allons d'abord enlever les doublons

In [80]:
# Suppression des doublons dans order_items
df_items = df_items.drop_duplicates()

# Suppression des doublons dans orders
df_orders = df_orders.drop_duplicates()

### Filtrage des données

Nous allons supprimer tout les frais livraison qui coute 0 euros et nous devons appliquer des clients qui ont été bien livrés leur produit

In [81]:
df_delivered_orders = df_orders.loc[df_orders["statut_commande"] == "delivered"]

### Taille des données

In [82]:
print(df_items.shape)
print(df_orders.shape)
print(df_delivered_orders.shape)

(112650, 7)
(99441, 8)
(96478, 8)

### Jointure des données à partir de la table order_id

Nous allons faire une jointure des données sur l'order id pour déterminer quels clients payent les frais de livraison pour chaque produit

In [83]:
# Jointure INNER JOIN à partir de la table order_id
merged_data = pd.merge(df_items, df_delivered_orders, on='identifiant_commande')

merged_data.head()

,identifiant_commande,identifiant_article_commande,identifiant_produit,identifiant_vendeur,date_limite_expedition,prix,valeur_fret,identifiant_client,statut_commande,timestamp_achat_commande,commande_approuvee_a,date_livraison_transporteur_commande,date_livraison_client_commande,date_livraison_estimee_commande
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29 00:00:00
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15 00:00:00
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05 00:00:00
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20 00:00:00
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17 00:00:00

In [84]:
merged_data['date_livraison_client_commande'] = pd.to_datetime(merged_data['date_livraison_client_commande'])

# Séparer les données sur les années, mois et jours
merged_data['annee_livraison_client'] = merged_data['date_livraison_client_commande'].dt.year.fillna(0).astype(int)
merged_data['mois_livraison_client'] = merged_data['date_livraison_client_commande'].dt.month.fillna(0).astype(int)
merged_data['jour_livraison_client'] = merged_data['date_livraison_client_commande'].dt.day.fillna(0).astype(int)

merged_data.head()

,identifiant_commande,identifiant_article_commande,identifiant_produit,identifiant_vendeur,date_limite_expedition,prix,valeur_fret,identifiant_client,statut_commande,timestamp_achat_commande,commande_approuvee_a,date_livraison_transporteur_commande,date_livraison_client_commande,date_livraison_estimee_commande,annee_livraison_client,mois_livraison_client,jour_livraison_client
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29 00:00:00,2017,9,20
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15 00:00:00,2017,5,12
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05 00:00:00,2018,1,22
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20 00:00:00,2018,8,14
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17 00:00:00,2017,3,1

In [85]:
# Jointure INNER JOIN à partir de la table identifiant_produit
merged_2_data = pd.merge(df_products, df_items, on='identifiant_produit')

In [86]:
merged_2_data.head()

,identifiant_produit,nom_categorie_produit,longueur_nom_produit,longueur_description_produit,quantite_photos_produit,poids_produit_g,longueur_produit_cm,hauteur_produit_cm,largeur_produit_cm,identifiant_commande,identifiant_article_commande,identifiant_vendeur,date_limite_expedition,prix,valeur_fret
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,e17e4f88e31525f7deef66779844ddce,1,5670f4db5b62c43d542e1b2d56b0cf7c,2018-04-30 17:33:54,10.91,7.39
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,5236307716393b7114b53ee991f36956,1,b561927807645834b59ef0d16ba55a24,2018-02-06 19:11:15,248.00,17.99
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,01f66e58769f84129811d43eefd187fb,1,7b07b3c7487f0ea825fc6df75abd658b,2018-07-11 21:30:20,79.80,7.82
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,143d00a4f2dde4e0364ee1821577adb3,1,c510bc1718f0f2961eaa42a23330681a,2018-08-07 09:10:13,112.30,9.54
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,86cafb8794cb99a9b1b77fc8e48fbbbb,1,0be8ff43f22e456b4e0371b2245e4d01,2018-04-17 01:30:23,37.90,8.29

In [87]:
merged_2_data.shape

(112650, 15)

In [88]:
df_merged = pd.merge(merged_2_data,df_traduction_products, on='nom_categorie_produit', how='left')
df_merged.drop(columns=['nom_categorie_produit'], inplace=True)

df_merged.head()

,identifiant_produit,longueur_nom_produit,longueur_description_produit,quantite_photos_produit,poids_produit_g,longueur_produit_cm,hauteur_produit_cm,largeur_produit_cm,identifiant_commande,identifiant_article_commande,identifiant_vendeur,date_limite_expedition,prix,valeur_fret,nom_categorie_produit_anglais
0,1e9e8ef04dbcff4541ed26657ea517e5,40.0,287.0,1.0,225.0,16.0,10.0,14.0,e17e4f88e31525f7deef66779844ddce,1,5670f4db5b62c43d542e1b2d56b0cf7c,2018-04-30 17:33:54,10.91,7.39,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,5236307716393b7114b53ee991f36956,1,b561927807645834b59ef0d16ba55a24,2018-02-06 19:11:15,248.00,17.99,art
2,96bd76ec8810374ed1b65e291975717f,46.0,250.0,1.0,154.0,18.0,9.0,15.0,01f66e58769f84129811d43eefd187fb,1,7b07b3c7487f0ea825fc6df75abd658b,2018-07-11 21:30:20,79.80,7.82,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,27.0,261.0,1.0,371.0,26.0,4.0,26.0,143d00a4f2dde4e0364ee1821577adb3,1,c510bc1718f0f2961eaa42a23330681a,2018-08-07 09:10:13,112.30,9.54,baby
4,9dc1a7de274444849c219cff195d0b71,37.0,402.0,4.0,625.0,20.0,17.0,13.0,86cafb8794cb99a9b1b77fc8e48fbbbb,1,0be8ff43f22e456b4e0371b2245e4d01,2018-04-17 01:30:23,37.90,8.29,housewares

In [89]:
df_merged.shape

(112650, 15)

In [90]:
df_merged['chiffre_affaires'] = df_merged['quantite_photos_produit'] * df_merged['prix']

In [112]:
# Calculer le chiffre d'affaires total
ca_total = df_merged['chiffre_affaires'].sum()

#### Conversion les numéro de mois en nom de mois

In [94]:
import calendar

calendar.month_name = [
    "", "Janvier", "Février", "Mars", "Avril", "Mai", "Juin",
    "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"
]

# Fonction pour convertir le numéro de mois en nom de mois
def num_to_month(num):
    return calendar.month_name[num]

# Appliquer la fonction à la colonne 'mois' du DataFrame
merged_data['mois_livraison_client'] = merged_data['mois_livraison_client'].apply(num_to_month)
merged_data.head()

,identifiant_commande,identifiant_article_commande,identifiant_produit,identifiant_vendeur,date_limite_expedition,prix,valeur_fret,identifiant_client,statut_commande,timestamp_achat_commande,commande_approuvee_a,date_livraison_transporteur_commande,date_livraison_client_commande,date_livraison_estimee_commande,annee_livraison_client,mois_livraison_client,jour_livraison_client
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29 00:00:00,2017,Septembre,20
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15 00:00:00,2017,Mai,12
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05 00:00:00,2018,Janvier,22
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20 00:00:00,2018,Août,14
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17 00:00:00,2017,Mars,1

Nous allons calculer le montant total des frais de livraison pour chaque client et de déterminer le montant le plus cher des frais de livraison

In [95]:
# Calcul du montant total des frais de transport pour chaque client
total_freight_per_customer = merged_data.groupby('identifiant_client')['valeur_fret'].sum()

# Créer un DataFrame pour les identifiants des clients et les frais de livraison
df_sorted_customers = pd.DataFrame({'identifiant_client': total_freight_per_customer.index,
                                    'valeur_fret': total_freight_per_customer.values})

#Filtrer les frais en prenant une plage de 100 à 250 
#df_sorted_customers = df_sorted_customers.loc[(df_sorted_customers["valeur_fret"] > 100) & (df_sorted_customers["valeur_fret"] < 250)]

# # Trier les clients par montant total des frais de livraison
# df_sorted_customers = df_sorted_customers.sort_values(by='valeur_fret', ascending=False)

# Affichage des premières lignes du nouveau DataFrame
df_sorted_customers.head()

                 identifiant_client  valeur_fret
0  00012a2ce6f8dcda20d059ce98491703        24.94
1  000161a058600d5901f007fab4c27140        12.51
2  0001fd6190edaaf884bcaf3d49edf079        15.43
3  0002414f95344307404f0ace7a26f1d5        29.45
4  000379cdec625522490c315e70c7a9fb        14.01

### Normalisation des données


On souhaite de normaliser les frais de livraison puisqu'on a besoin de déterminer le cluster des clients en 3 segments

In [96]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# Normalisation des données
scaler = StandardScaler()
X = scaler.fit_transform(df_sorted_customers[['valeur_fret']])

### Utilisation du clustering K-means

On utilisera l'algorithme de K-means pour déterminer des groupes de clients similaires en fonction du montant total des frais de livraison. Par exemple, il peut identifier un groupe de clients qui paient des frais de livraison élevés, un groupe de clients avec des frais de livraison moyens, et un groupe de clients avec des frais de livraison bas.

In [97]:
# Clustering des clients en 20 segments
kmeans = KMeans(n_clusters=3, random_state=42)
df_sorted_customers['segment'] = kmeans.fit_predict(X)

In [98]:
df_sorted_customers.head()

                 identifiant_client  valeur_fret  segment
0  00012a2ce6f8dcda20d059ce98491703        24.94        0
1  000161a058600d5901f007fab4c27140        12.51        0
2  0001fd6190edaaf884bcaf3d49edf079        15.43        0
3  0002414f95344307404f0ace7a26f1d5        29.45        0
4  000379cdec625522490c315e70c7a9fb        14.01        0

### Visualisation des données sur Dash / Plotly

#### Première visualisation sur la répartition des groupes de catégories de frais 

Dans cette visualisation, on peut identifier un groupe de clients qui paient des frais de livraison élevés, un groupe de clients avec des frais de livraison moyens, et un groupe de clients avec des frais de livraison bas.
Les clients qui paient des frais de livraison élevés peuvent bénéficier de programmes de fidélisation ou de promotions spéciales pour encourager des achats répétés.

Donc à l'utilisation de K-means permet aux entreprises de mieux comprendre leur base de clients, d'adapter leurs stratégies commerciales en conséquence, et d'optimiser leurs opérations pour répondre aux besoins et aux comportements des clients.


Niveau Bas : La majorité des clients ont payé des frais de livraison considérés comme bas. Cela pourrait indiquer que la plupart des clients ont choisi des options de livraison économiques ou ont bénéficié de promotions ou de réductions sur les frais de livraison. <br>

Niveau Moyen: Environ un cinquième des clients ont payé des frais de livraison de niveau moyen. Cela suggère qu'une proportion significative de votre clientèle est prête à payer des frais de livraison légèrement plus élevés pour des services de livraison plus rapides ou plus fiables, mais ils recherchent toujours des options relativement abordables. <br>

Niveau Haut: Seule une petite fraction des clients ont payé des frais de livraison élevés. Cela peut indiquer que cette partie de la clientèle est prête à payer un prix plus élevé pour des services de livraison premium, tels que la livraison express ou des options de suivi avancées. Ces clients peuvent valoriser la rapidité et la fiabilité de la livraison plus que le coût. <br>


Valeur fret = poids de livraison

In [99]:
# On définit les plages de valeurs de frais entre 100 à 250  
seuils = [100,150,200,250] 

# Définition des catégories de frais en fonction des plages
categories = ['bas', 'milieu', 'élevés']

# Assigner une catégorie à chaque ligne en fonction de la valeur de 'valeur_fret'
df_sorted_customers['categorie_frais'] = pd.cut(df_sorted_customers['valeur_fret'], bins=seuils, labels=categories, right=False)

#On doit nettoyer les données sur Categorie_frais pour retirer tout les données manquantes qui ne trouve pas dans le sueil 
df_sorted_customers= df_sorted_customers.dropna()

In [100]:
import plotly.express as px
 
# Création de la visualisation avec une taille de figure plus grande
fig = px.scatter(df_sorted_customers, y='valeur_fret', color='categorie_frais', color_discrete_map={'bas': 'darkgreen', 'milieu': 'darkblue', 'élevés': 'darkred'},
                 labels={'valeur_fret': 'Montant total des frais de livraison'},
                 title="Segmentation des clients par frais de livraison")

fig.update_layout(
    xaxis=dict(title=None, visible=False),
    yaxis=dict(title="Montant total des frais de livraison en Reais (RIs)"),
    width=800, height=600,  # Taille de la figure
)

fig.show()

#### Visualisation pour déterminer le pourcentage des répartitions des clients ayant payé des frais élevés, milieu et bas par rapport à la période de l'année, du mois et du jour

On doit faire une deuxième jointure pour récupérer les différents dates pour visualiser notre graphe

In [101]:
#Jointure entre le dataframe df_sorted_customers et merged_data 
df_sorted_customers = pd.merge(df_sorted_customers, merged_data[['identifiant_client', 'annee_livraison_client','mois_livraison_client','jour_livraison_client']], 
                               on='identifiant_client')
df_sorted_customers.head()

,identifiant_client,valeur_fret,segment,categorie_frais,annee_livraison_client,mois_livraison_client,jour_livraison_client
0,000598caf2ef4117407665ac33275130,148.71,1,bas,2018,Août,20
1,005196c65bab2861e397cc85bc7664bf,144.65,1,bas,2018,Février,9
2,0062859a8f89e25c6b0e8dc905ccc59d,123.44,1,bas,2018,Avril,6
3,016025d2b068f90498479376f9bfcca1,180.96,1,milieu,2017,Octobre,11
4,016025d2b068f90498479376f9bfcca1,180.96,1,milieu,2017,Octobre,11

In [111]:
import dash
from dash import dcc, html
from dash.dependencies import Input, Output
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Initialisation de l'application Dash
app = dash.Dash(__name__)

# Définir une fonction pour filtrer le DataFrame en fonction des années et des mois sélectionnés
def filter_dataframe(df_sorted_customers , selected_years, selected_months):
    filtered_df = df_sorted_customers[df_sorted_customers ['annee_livraison_client'].isin(selected_years)]
    if selected_months:
        filtered_df = filtered_df[filtered_df['mois_livraison_client'].isin(selected_months)]
    return filtered_df


# Supposons que vous ayez une colonne 'valeur_fret' dans votre dataframe 'df_sorted_customers'

# Mise en forme de l'application Dash
app.layout = html.Div([
    html.H1("Visualisation graphique sur le profil des clients"),
    
    # Case à cocher pour filtrer les années
    html.Div([
        html.H3("Filtrer par année:"),
        dcc.Checklist(
            id='year-filter',
            options=[
                {'label': '2016', 'value': 2016},
                {'label': '2017', 'value': 2017},
                {'label': '2018', 'value': 2018}
            ],
            value=[2016, 2017, 2018],  # Sélectionner toutes les années par défaut
            labelStyle={'display': 'inline-block'}
        ),
    ]),
    

    # Case à cocher pour filtrer par mois
    html.Div([
        html.H3("Filtrer par mois:"),
        dcc.Checklist(
            id='month-filter',
            options=[
                {'label': 'Janvier', 'value': 'Janvier'},
                {'label': 'Février', 'value': 'Février'},
                {'label': 'Mars', 'value': 'Mars'},
                {'label': 'Avril', 'value': 'Avril'},
                {'label': 'Mai', 'value': 'Mai'},
                {'label': 'Juin', 'value': 'Juin'},
                {'label': 'Juillet', 'value': 'Juillet'},
                {'label': 'Août', 'value': 'Août'},
                {'label': 'Septembre', 'value': 'Septembre'},
                {'label': 'Octobre', 'value': 'Octobre'},
                {'label': 'Novembre', 'value': 'Novembre'},
                {'label': 'Décembre', 'value': 'Décembre'},
                # Ajoutez les autres mois ici
            ],
            value=[],  # Sélectionner aucun mois par défaut
            labelStyle={'display': 'inline-block'}
        ),
    ]),
    dcc.Graph(id='CA-graph'),
    dcc.Graph(id='segmentation-graph'),
    dcc.Graph(id='second-graph')
])


# Callback pour mettre à jour le graphique en fonction des années, mois et jours sélectionnés
@app.callback(
    Output('segmentation-graph', 'figure'),
    [Input('year-filter', 'value'),
     Input('month-filter', 'value')
    ]
)
def update_graph(selected_years, selected_months):
    
    filtered_df = filter_dataframe(df_sorted_customers, selected_years, selected_months)
    # Compter le nombre de clients dans chaque catégorie de frais
    repartition_frais = filtered_df['categorie_frais'].value_counts()

    # Calculer les pourcentages des frais
    pourcentage_bas = (repartition_frais['bas'] / len(filtered_df)) * 100
    pourcentage_milieu = (repartition_frais['milieu'] / len(filtered_df)) * 100
    pourcentage_eleves = (repartition_frais['élevés'] / len(filtered_df)) * 100

    # Créer une nouvelle visualisation pour afficher les pourcentages
    fig_pourcentage = px.pie(names=['Bas', 'Milieu', 'Élevés'], 
                             values=[pourcentage_bas, pourcentage_milieu, pourcentage_eleves], 
                             title="Répartition des niveaux de frais de livraison sur Olist",
                             labels={'value': 'Pourcentage', 'names': 'Catégorie de frais'})
    
    fig_pourcentage.update_layout(
        width=500, height=400  # Taille de la figure
    )
    
    return fig_pourcentage


# Callback pour mettre à jour le deuxième graphique
@app.callback(
    Output('second-graph', 'figure'),
    [Input('year-filter', 'value'),
     Input('month-filter', 'value')
    ]  # Entrée factice
)
def update_second_graph(selected_years, selected_months):
    filtered_df = filter_dataframe(df_sorted_customers, selected_years, selected_months)

    
    # Création de la visualisation avec une taille de figure plus grande
    fig = px.scatter(filtered_df,x='identifiant_client', y='valeur_fret', color='categorie_frais', color_discrete_map={'bas': 'darkgreen', 'milieu': 'darkblue', 'élevés': 'darkred'},
                    title="Segmentation des clients par frais de livraison")
    
    fig.update_layout(
        xaxis=dict(title='Identifiant du client',showline=True, showticklabels=False, showgrid=False,title_standoff=80),
        yaxis=dict(title="Montant total des frais de livraison en Reais (RIs)"),
        width=800, height=600,  # Taille de la figure
    )

    return fig

# Callback pour mettre à jour le deuxième graphique
@app.callback(
    Output('CA-graph', 'figure'),
    [Input('year-filter', 'value'),
     Input('month-filter', 'value')
    ]  # Entrée factice
)

def update_third_graph(selected_years, selected_months):
    
    filtered_df = filter_dataframe(df_sorted_customers, selected_years, selected_months)

    # Créer un graphique à l'aide de Plotly
    fig = make_subplots(rows=1, cols=1)

    # Ajouter les jauges pour chaque statistique
    fig.add_trace(go.Indicator(
        mode = "number",
        value = ca_total,
        title = {"text": "Total Chiffre d'affaires"},
        domain = {'row': 1, 'column': 1}
    ))

    # Mettre en forme le layout du graphique
    fig.update_layout(height=400, width=800)

    # Afficher le graphique
    return fig

# Exécution de l'application Dash
if __name__ == '__main__':
    app.run_server(debug=True)